name: Remote SSH
on:
  push:
    branches:
        - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd programming/games-VPlan_FR/
          
          kill -INT (lsof -t nohup.out)

          git pull

          npm install
          npm run build
          
          sudo service apache2 restart

          rm nohup.out
          nohup node build > nohup.out 2> nohup.err < /dev/null &

          disown (lsof -t nohup.out)